default_stages: [pre-commit, pre-push, manual]
exclude: ^python/sglang/srt/grpc/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
    - id: yapf
      args: [--in-place, --verbose]
  - repo: https://github.com/crate-ci/typos
    rev: v1.35.5
    hooks:
    - id: typos
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
